version: "3"
services:
  app:
    build: .
    tty: true
    command: node /app/index.js "/home/pudding/Documents/ramdisk/test/"
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - /home/pudding/Documents/ramdisk/:/input/